Algoritmo "- Média de Três Valores"
// Disciplina: Lógica de Programação
// Professor: Jailson Costa
// Descrição: Leia a de um e calcule sua.
// Autor: Gabriel Henrique Rocha
// Data atual  : 28/03/2026

Var
valor01,valor02,valor03, media: real


Inicio
     escreval("Digite o primeiro valor: ")
     leia(valor01)
     escreval("Digite o segundo valor: ")
     leia(valor02)
     escreval("digite o terceiro valor: ")
     leia(valor03)
     media<- (valor01 + valor02 + valor03) / 3
     escreval("A média do três valores é: ", media)

Fimalgoritmo