Algoritmo "Area do quadrado"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson costa dos santos
// Descrição   : Área do quadrado
// Autor(a)    : Gabriel Henrique Alves Rocha
// Data atual  : 27/03/2026
Var
// Seção de Declarações das variáveis 
area,lado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva("Digite o Lado do Quadrado: ")
 leia(lado)
 area <- lado*lado
 Escreva("Área do quadrado é de: ", area)
Fimalgoritmo