Algoritmo "Consumo Médio de Combustível "
// Disciplina   : Lógica de Programação
// Professor   :   Jailson Costa Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Henrique Alves Rocha
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis 
distancia,combustivel,consumo: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite a Distancia em km")
leia(distancia)
escreval("Digite o combustivel em litros")
leia(combustivel)
consumo<-   distancia/combustivel
escreval("O consumo médio é de : ", consumo)
Fimalgoritmo