Algoritmo "Conversão de Temperatura  "
// Disciplina   : Lógica de Programação
// Professor   :  Jailson Costa Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Henrique Alves Rocha
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis 
celsius,fahrenheit: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite a temperatura em CElsius")
leia(celsius)
fahrenheit<-  (celsius*9/5)+32
escreval("A temperatura em fahrenheit é de: ", fahrenheit)
Fimalgoritmo