Algoritmo "Conversão de Metros para Centímetros"
// Disciplina: Lógica de Programação
// Professor: Jailson Costa
// Descrição: Leia a de um e calcule sua.
// Autor: Gabriel Henrique Rocha
// Data atual  : 28/03/2026

Var
metros, centimetros: real


Inicio
     escreval("Digite o valor em metros: ")
     leia(metros)
     centimetros<- metros * 100
     escreval("Valor convertido para centímetros: ", centimetros)

Fimalgoritmo