Algoritmo "Divisão"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Solicita dois números para o usuário, soma e exibe o resultado
// Autor(a)    : Gabriel Henrique Alves Rocha
// Data atual  : 26/03/2026
Var
numero01:real
numero02:real
resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite uma soma ")
leia(numero01)
escreva("Digite outro numero ")
leia(numero02)
resultado <- numero01 / numero02
escreva("resultado", resultado)
Fimalgoritmo