Algoritmo "Idade em Meses e Dias"
// Disciplina: Lógica de Programação
// Professor: Jailson Costa
// Descrição: Leia a de um e calcule sua.
// Autor: Gabriel Henrique Rocha
// Data atual  : 28/03/2026

Var
idade,meses,dias: real


Inicio
     escreval("Dgite sua idade ")
     leia(idade)
    meses<- idade * 12
    dias<- idade * 365
     escreval("sua idade convertida em meses", meses)
     escreval("sua idade convertida em dias", dias)

Fimalgoritmo