Algoritmo "Soma"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Solicita dois números para o usuário, soma e exibe o resultado
// Autor(a)    : Gabriel Henrique Alves Rocha
// Data atual  : 26/03/2026
Var
nome:caractere
sobrenome:caractere
nomecompleto:caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite seu nome ")
leia(nome)
escreva("Digite seu sobrenome ")
leia(sobrenome)
nomecompleto <- nome + " " + sobrenome
escreva("Olá ", nomecompleto)
Fimalgoritmo