Algoritmo "Area do Retângulo"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson costa dos santos
// Descrição   : Área do retângulo
// Autor(a)    : Gabriel Henrique Alves Rocha
// Data atual  : 27/03/2026
Var
// Seção de Declarações das variáveis 
base,altura,resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite uma base: ")
Leia(base)
Escreva("Digite uma Altura: ")
Leia(altura)
resultado <- 2 *( base + altura )
Escreva("A Área do retângulo ", resultado)
Fimalgoritmo