Algoritmo "Área do Círculo "
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson costa dos santos
// Descrição   : Área do Círculo
// Autor(a)    : Gabriel Henrique Alves Rocha
// Data atual  : 27/03/2026
Var
// Seção de Declarações das variáveis 
area,raio,resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Digite uma base: ")
Leia(area)
resultado <- pi * (raio * 2)
Escreva("A Área do retângulo ", resultado)
Fimalgoritmo