Algoritmo "Perímetro de um Retângulo"
// Disciplina   : Lógica de Programação
// Professor   :  Jailson Costa Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Henrique Alves Rocha
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis 
largura,altura,perimetro: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite a altura de um retângulo")
leia(altura)
escreval("Digite a largura")
leia(largura)
perimetro<- 2*(largura + altura)
escreval("O perímetro é de: ", perimetro)
Fimalgoritmo