Algoritmo "Sucessor"
// Disciplina   : [Lógica de Programação]
// Professor   : Jailson
// Descrição   : Solicita dois números para o usuário, soma e exibe o resultado
// Autor(a)    : Gabriel Henrique Alves Rocha
// Data atual  : 26/03/2026
Var
numero01:real
resultado:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Digite um número ")
leia(numero01)
resultado <- numero01 + 1
escreva("resultado", resultado)
Fimalgoritmo