Algoritmo "Troca de Valores "
// Disciplina   : Lógica de Programação
// Professor   :  Jailson Costa Santos
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Henrique Alves Rocha
// Data atual  : 30/03/2026
Var
// Seção de Declarações das variáveis 
valorA,valorB,troca: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite e lembre-se do valor A")
leia(valorA)
escreval("Digite e lembre-se do valor B")
leia(valorB)

escreval("O valor A se tornou ", valorB)
escreval("O valor B se tornou ", valorA)
Fimalgoritmo