Algoritmo "Valor do Desconto"
// Disciplina: Lógica de Programação
// Professor: Jailson Costa
// Descrição: Leia a de um e calcule sua.
// Autor: Gabriel Henrique Rocha
// Data atual  : 28/03/2026

Var
produto, desconto, preco:real


Inicio
escreval("Digite o preço do produto: ")
leia(preco)
escreval("Digite a quantidade")
leia(quantidade)

   total<- preco * quantidade
     escreval("Você irá pagar: ", total)

Fimalgoritmo