Algoritmo "Área do Losango"
// Disciplina: Lógica de Programação
// Professor: Jailson Costa
// Descrição: Leia a de um e calcule sua.
// Autor: Gabriel Henrique Rocha
// Data atual  : 28/03/2026

Var
diagonalMaior, diagonalMenor, area: real


Inicio
     escreval("Digite o valor da area do losango: ")
     leia(diagonalMaior)
     escreval("Digite o outro valor: ")
     leia(diagonalMenor)
     area<- (diagonalMaior * diagonalMenor)/2
     escreval("A área do losango é: ", area)

Fimalgoritmo