Algoritmo "Área do Triângulo"
// Disciplina: Lógica de Programação
// Professor: Jailson Costa
// Descrição: Leia a de um e calcule sua.
// Autor: Gabriel Henrique Rocha
// Data atual  : 28/03/2026

Var
base: real
altura: real
area: real

Inicio
     escreval("Digite o valor de base: ")
     leia(base)
     escreval("Digite o valor de altura: ")
     leia(altura)
     area<- (base * altura) / 2
     escreval("A Área do Triângulo é: ", area)

Fimalgoritmo