Algoritmo "Área do Trapézio"
// Disciplina: Lógica de Programação
// Professor: Jailson Costa
// Descrição: Leia a de um e calcule sua.
// Autor: Gabriel Henrique Rocha
// Data atual  : 28/03/2026

Var
baseMaior, baseMenor, altura,area: real


Inicio
     escreval("Digite o valor da base Maior da Área do Trapézio: ")
     leia(baseMaior)
     escreval("Digite o valor da base Menor da Área do Trapézio: ")
     leia(baseMenor)
     escreval("Digite o valor da altura: ")
     leia(altura)
     area<- (baseMaior * baseMenor) * 2 / 2
     escreval("A área do Área do Trapézio: ", area)

Fimalgoritmo