Algoritmo "Área e Perímetro de um Quadrado"
// Disciplina: Lógica de Programação
// Professor: Jailson Costa
// Descrição: Leia a de um e calcule sua.
// Autor: Gabriel Henrique Rocha
// Data atual  : 28/03/2026

Var
perimetro,lado,area: real


Inicio
     escreval("Digite o valor da base da Área e Perímetro de um Quadrado: ")
     leia(lado)
     escreval("Digite o valor da altura do Área e Perímetro de um Quadrado: ")
     leia(perimetro)
     area<- lado * 2
     perimetro <- 4 *lado
     escreval("A área do Área e Perímetro de um Quadrado: ", area, perimetro)

Fimalgoritmo