Algoritmo "Área do Paralelogramo"
// Disciplina: Lógica de Programação
// Professor: Jailson Costa
// Descrição: Leia a de um e calcule sua.
// Autor: Gabriel Henrique Rocha
// Data atual  : 28/03/2026

Var
base, altura,area: real


Inicio
     escreval("Digite o valor da base da Área do Paralelogramo: ")
     leia(base)
     escreval("Digite o valor da altura do Área do Paralelogramo: ")
     leia(altura)
     area<- base * altura
     escreval("A área do Área do Paralelogramo: ", area)

Fimalgoritmo