Algoritmo "ContadoraAoContrario"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa do Santos
// Descrição   :   Programa faz e emprime contagem de 10 até 1
// Autor(a)    : Gabriel Henrique Alves Rocha
// Data atual  : 14/04/2026
Var
contadora: inteiro

Inicio
Escreval ("Exemplo de Laço de repetição Para")

para contadora de 100 ate 1 passo -1 faça
    Escreval (contadora)
fimpara


Fimalgoritmo