Algoritmo "Contadora"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa do Santos
// Descrição   :   Programa faz e emprime contagem de 1 até 10
// Autor(a)    : Gabriel Henrique Alves Rocha
// Data atual  : 14/04/2026
Var
contadora: inteiro

Inicio
Escreval ("Exemplo de Laço de repetição Para")

para contadora de 1 ate 100000 passo 1 faça
    Escreval (contadora)
fimpara


Fimalgoritmo