Algoritmo "Cronometro"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson Costa do Santos
// Descrição   : Cronometro
// Autor(a)    : Gabriel Henrique Alves Rocha
// Data atual  : 14/04/2026
Var
minutos, segundos: inteiro

Inicio
Escreval ("Exemplo do cronometro")

para minutos de 0 ate 59 passo 1 faça
     para segundos de 0 ate 59 passo 1 faça
    Escreval (minutos, " : ", segundos)
    fimpara
fimpara


Fimalgoritmo